services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./todo-app/backend/Dockerfile
    dockerContext: ./todo-app/backend

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./todo-app/frontend/Dockerfile
    dockerContext: ./todo-app/frontend